pragma Singleton
import QtQuick

QtObject {
    // ============================================================================
    // MATUGEN SEMANTIC TOKENS (Material Design 3)
    // ============================================================================
    // These values are generated by matugen from your wallpaper
    
    // --- Primary Colors (Main brand color) ---
    readonly property color primary: "#c0c1ff"
    readonly property color on_primary: "#282a60"
    readonly property color primary_container: "#3f4178"
    readonly property color on_primary_container: "#e1e0ff"
    readonly property color primary_fixed: "#e1e0ff"
    readonly property color primary_fixed_dim: "#c0c1ff"
    readonly property color on_primary_fixed: "#12144b"
    readonly property color on_primary_fixed_variant: "#3f4178"
    
    // --- Secondary Colors (Supporting color) ---
    readonly property color secondary: "#c5c4dd"
    readonly property color on_secondary: "#2e2f42"
    readonly property color secondary_container: "#454559"
    readonly property color on_secondary_container: "#e2e0f9"
    readonly property color secondary_fixed: "#e2e0f9"
    readonly property color secondary_fixed_dim: "#c5c4dd"
    readonly property color on_secondary_fixed: "#191a2c"
    readonly property color on_secondary_fixed_variant: "#454559"
    
    // --- Tertiary Colors (Third accent) ---
    readonly property color tertiary: "#e8b9d4"
    readonly property color on_tertiary: "#46263b"
    readonly property color tertiary_container: "#5f3c52"
    readonly property color on_tertiary_container: "#ffd8ed"
    readonly property color tertiary_fixed: "#ffd8ed"
    readonly property color tertiary_fixed_dim: "#e8b9d4"
    readonly property color on_tertiary_fixed: "#2e1125"
    readonly property color on_tertiary_fixed_variant: "#5f3c52"
    
    // --- Error Colors ---
    readonly property color error: "#ffb4ab"
    readonly property color on_error: "#690005"
    readonly property color error_container: "#93000a"
    readonly property color on_error_container: "#ffdad6"
    
    // --- Background Colors ---
    readonly property color background: "#131318"
    readonly property color on_background: "#e4e1e9"
    
    // --- Surface Colors (5-level elevation system) ---
    readonly property color surface: "#131318"
    readonly property color on_surface: "#e4e1e9"
    readonly property color surface_variant: "#46464f"
    readonly property color on_surface_variant: "#c7c5d0"
    
    readonly property color surface_dim: "#131318"
    readonly property color surface_bright: "#39383f"
    readonly property color surface_container_lowest: "#0e0e13"
    readonly property color surface_container_low: "#1b1b21"
    readonly property color surface_container: "#1f1f25"
    readonly property color surface_container_high: "#2a292f"
    readonly property color surface_container_highest: "#35343a"
    
    // --- Outline Colors (Borders) ---
    readonly property color outline: "#918f9a"
    readonly property color outline_variant: "#46464f"
    
    // --- Inverse Colors (for dark/light theme switching) ---
    readonly property color inverse_surface: "#e4e1e9"
    readonly property color inverse_on_surface: "#303036"
    readonly property color inverse_primary: "#575992"
    
    // --- Scrim & Shadow ---
    readonly property color scrim: "#000000"
    readonly property color shadow: "#000000"
    
    // ============================================================================
    // TRANSPARENT VARIANTS - FOR BLUR EFFECTS
    // ============================================================================
    // Use these with Hyprland blur for beautiful frosted glass effects!
    // Light = 60-65% opacity (subtle blur, good visibility)
    // Medium = 75-80% opacity (balanced blur, most common)
    // Heavy = 90-92% opacity (strong blur, near-opaque)

    // --- Primary Transparencies ---
    readonly property color primary_transparent_light: Qt.rgba(primary.r, primary.g, primary.b, 0.25)
    readonly property color primary_transparent_medium: Qt.rgba(primary.r, primary.g, primary.b, 0.40)
    readonly property color primary_transparent_heavy: Qt.rgba(primary.r, primary.g, primary.b, 0.60)

    // --- Surface Transparencies (for backgrounds) ---
    readonly property color surface_transparent_light: Qt.rgba(surface.r, surface.g, surface.b, 0.50)
    readonly property color surface_transparent_medium: Qt.rgba(surface.r, surface.g, surface.b, 0.70)
    readonly property color surface_transparent_heavy: Qt.rgba(surface.r, surface.g, surface.b, 0.85)

    // --- Surface Container Transparencies (for main panels/popups) ---
    readonly property color surface_container_transparent_light: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.60)
    readonly property color surface_container_transparent_medium: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.75)
    readonly property color surface_container_transparent_heavy: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.90)

    // --- Surface Container Low Transparencies (for lower elevation cards) ---
    readonly property color surface_container_low_transparent_light: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.50)
    readonly property color surface_container_low_transparent_medium: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.65)
    readonly property color surface_container_low_transparent_heavy: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.80)

    // --- Surface Container High Transparencies (for higher elevation cards) ---
    readonly property color surface_container_high_transparent_light: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.70)
    readonly property color surface_container_high_transparent_medium: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.85)
    readonly property color surface_container_high_transparent_heavy: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.95)

    // --- Scrim Transparencies (for modal overlays) ---
    readonly property color scrim_transparent_light: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.15)
    readonly property color scrim_transparent_medium: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.45)
    readonly property color scrim_transparent_heavy: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.65)
    
    // ============================================================================
    // SPACING SYSTEM
    // ============================================================================
    
    readonly property QtObject spacing: QtObject {
      readonly property int xs: 4
      readonly property int sm: 8
      readonly property int md: 12
      readonly property int lg: 18
      readonly property int xl: 26 
      readonly property int xxl: 48
    }
    
    // ============================================================================
    // PADDING SYSTEM
    // ============================================================================
    
    readonly property QtObject padding: QtObject {
      readonly property int xs: 4
      readonly property int sm: 8
      readonly property int md: 12
      readonly property int lg: 18
      readonly property int xl: 20
    }
    
    // ============================================================================
    // TYPOGRAPHY SYSTEM
    // ============================================================================
    
    readonly property QtObject typography: QtObject {
      readonly property string fontFamily: "Google Sans"
      readonly property string fontFamilyDisplay: "Google Sans"
        
      readonly property int xs: 10
      readonly property int sm: 12
      readonly property int md: 14
      readonly property int lg: 16
      readonly property int xl: 18
      readonly property int xxl: 24
      readonly property int xxxl: 32
        
      readonly property int weightNormal: 400
      readonly property int weightMedium: 500
      readonly property int weightBold: 700
    }
    
    // ============================================================================
    // SHAPE SYSTEM (Border Radius)
    // ============================================================================
    
    readonly property QtObject radius: QtObject {
      readonly property int none: 0
      readonly property int sm: 6
      readonly property int md: 12
      readonly property int lg: 20
      readonly property int xl: 32 
      readonly property int xxl: 40
      readonly property int full: 9999
    }
    
    // ============================================================================
    // COMPONENT TOKENS
    // ============================================================================
    
    readonly property QtObject component: QtObject {
      readonly property int barHeight: 26
      readonly property int workspaceIndicatorSize: 10
      readonly property int buttonHeight: 36
      readonly property int inputHeight: 40
    }
    
    // ============================================================================
    // LEGACY ALIASES (for backward compatibility)
    // ============================================================================
    // These allow your existing code to work without changes
    
    readonly property color accent: primary
    readonly property color accentTransparent: primary_transparent
    readonly property color accentFixed: primary_fixed
    readonly property color bg0: surface
    readonly property color bg0transparent: surface_transparent
    readonly property color bg1: surface_container
    readonly property color bg1transparent: surface_container_transparent
    readonly property color bg1transparentLauncher: surface_container_transparent_medium
    readonly property color bg2: surface_container_low
    readonly property color bg2transparent: surface_container_low_transparent_medium
    readonly property color bgBright: surface_bright
    readonly property color bgDim: surface_dim
    readonly property color fg: on_surface
    readonly property color fgStrong: on_surface
    readonly property color fgMuted: on_surface_variant
    readonly property color border: outline
    readonly property color borderStrong: primary
    readonly property color borderDim: outline_variant
    readonly property color backgroundTransparent: surface_transparent
    
    // Spacing aliases
    readonly property int spacingXSmall: spacing.xs
    readonly property int spacingSmall: spacing.sm
    readonly property int spacingMedium: spacing.md
    readonly property int spacingLarge: spacing.lg
    readonly property int spacingXLarge: spacing.xl
    readonly property int spacingXS: spacing.xs
    readonly property int spacingS: spacing.sm
    readonly property int spacingM: spacing.md
    readonly property int spacingL: spacing.lg
    readonly property int spacingXL: spacing.xl
    
    // Margin aliases
    readonly property int marginXSmall: padding.xs
    readonly property int marginSmall: padding.sm
    readonly property int marginMedium: padding.md
    readonly property int marginLarge: padding.lg
    readonly property int marginXLarge: padding.xl
    readonly property int marginXS: padding.xs
    readonly property int marginS: padding.sm
    readonly property int marginM: padding.md
    readonly property int marginL: padding.lg
    readonly property int marginXL: padding.xl
    
    // Font aliases
    readonly property string fontFamily: typography.fontFamily
    readonly property int fontSizeXSmall: typography.xs
    readonly property int fontSizeSmall: typography.sm
    readonly property int fontSizeMedium: typography.md
    readonly property int fontSizeLarge: typography.lg
    readonly property int fontSizeXLarge: typography.xl
    readonly property int fontSizeXS: typography.xs
    readonly property int fontSizeS: typography.sm
    readonly property int fontSizeM: typography.md
    readonly property int fontSizeL: typography.lg
    readonly property int fontSizeXL: typography.xl
    
    // Radius aliases
    readonly property int radiusSmall: radius.sm
    readonly property int radiusMedium: radius.md
    readonly property int radiusLarge: radius.lg
    readonly property int radiusXLarge: radius.xl
    
    // Component aliases
    readonly property int barHeight: component.barHeight
    readonly property int workspaceIndicatorSize: component.workspaceIndicatorSize
}
